# Generated by Django 5.0.3 on 2024-03-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="javafile",
            name="code_line_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="javafile",
            name="comment_deviation_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="javafile",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="javafile",
            name="function_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="javafile",
            name="javadoc_comment_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="javafile",
            name="loc",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="javafile",
            name="other_comment_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
