# Generated by Django 5.0.3 on 2024-04-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_javafile_code_line_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="javafile",
            name="repo_url",
            field=models.URLField(default="https://default.url"),
        ),
    ]
